name: aimaze
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_router: ^2.0.0-alpha+22
  rxdart: ^0.23.1

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  effective_dart: ^1.2.1
  mockito: ^4.1.1
  test: ^1.6.0
